/* UI owns the shared patch maps. Every recipe renders through the same engine. */
(function(){'use strict';
const P=BCPrimitives,E=BCLogo,$=id=>document.getElementById(id),R=JSON.parse($('reference-data').textContent),STORAGE='bc-shared-primitives-v5';
let state=E.recipeState('long-wildfire'),mode='design',current,revision=0,toastTimer,renderTimer;
let alignment={scale:1,x:0,y:0};
try{const raw=localStorage.getItem(STORAGE);if(raw)state=E.normalise(JSON.parse(raw));}catch{}
const label=s=>s.replace(/-/g,' ');
function select(el,entries){el.replaceChildren(...entries.map(([value,text])=>{const o=document.createElement('option');o.value=value;o.textContent=text;return o;}));}
select($('recipe'),P.RECIPES.filter(x=>!x.excluded).map(x=>[x.id,x.name]));
for(const [id,table]of Object.entries({crest:P.CRESTS,tab:P.TABS,layout:P.LOCKUPS,theme:P.THEMES,typeRole:P.ROLES,typeSlot:P.SLOTS}))select($(id),Object.keys(table).map(k=>[k,label(k)]));
select($('typeFace'),Object.entries(P.FACES).map(([id,f])=>[id,f.label]));
$('typeRole').value='crest-condensed';$('typeSlot').value='long-lower';
function toast(s,error=false){$('toast').textContent=s;$('toast').classList.add('show');$('toast').style.background=error?'#813e32':'';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch{}}
const fieldLabels={upper:'Upper crest wording',lower:'Lower / ministry wording',service:'Service tab wording',word:'Acronym / wordmark',descriptor:'Descriptor',district:'District (optional)',lines:'One word or line per row',branch:'Branch strip wording'};
function fields(){const l=P.LOCKUPS[state.layout],tab=P.TABS[state.tab];let keys=[];
 if(l.kind!=='wordmark')keys.push('upper','lower');if(tab.slot&&l.kind!=='wordmark')keys.push('service');if(['horizontal','stacked','wordmark'].includes(l.kind))keys.push('word','descriptor','district');if(l.kind==='words')keys.push('lines');if(l.kind==='strip')keys.push('branch');
 $('contentFields').replaceChildren(...keys.map(k=>{const w=document.createElement('label');w.textContent=fieldLabels[k];const input=document.createElement(['lower','lines','branch'].includes(k)?'textarea':'input');input.value=state.content[k]||'';input.id='content-'+k;input.dataset.content=k;input.maxLength=320;if(input.tagName==='TEXTAREA')input.rows=k==='lines'?3:2;input.addEventListener('input',()=>{state.content[k]=input.value;schedule();});w.append(input);return w;}));
}
function sync(){for(const k of['recipe','crest','tab','layout','theme'])$(k).value=state[k];$('autoProfile').checked=state.autoProfile;$('outputWidth').value=state.outputWidth;fields();syncRole();syncSlot();}
function syncRole(){const id=$('typeRole').value,r=E.role(id,state);$('typeFace').value=r.face;$('roleCap').value=r.capScale;$('roleTracking').value=r.trackingEm;const uses=E.dependencies(id);$('roleUses').textContent='Shared by '+uses.length+' reference recipes: '+(uses.join(' · ')||'none in this family')+'.';}
function syncSlot(){const id=$('typeSlot').value,t=E.slot(id,state);$('slotCap').value=t.cap;$('slotTracking').value=t.tracking;for(const[k,field]of[['rx','slotRX'],['ry','slotRY']]){$(field).value=t[k]||'';$(field).disabled=t.side==='flat';}}
function schedule(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>refresh(),90);}
function startRecipe(id){if(P.recipe(id).excluded)throw Error('This distorted reference is excluded.');state=E.recipeState(id,state);alignment={scale:1,x:0,y:0};$('refScale').value=1;$('refX').value=0;$('refY').value=0;sync();refresh();}
$('recipe').addEventListener('change',()=>startRecipe($('recipe').value));
for(const k of['crest','tab','layout','theme'])$(k).addEventListener('change',()=>{state[k]=$(k).value;fields();refresh();});
$('autoProfile').addEventListener('change',()=>{state.autoProfile=$('autoProfile').checked;refresh();});
$('resetRecipe').onclick=()=>startRecipe(state.recipe);
$('typeRole').onchange=syncRole;$('typeSlot').onchange=syncSlot;
function changeRole(){const id=$('typeRole').value;state.roles[id]={face:$('typeFace').value,capScale:Number($('roleCap').value),trackingEm:Number($('roleTracking').value)};state=E.normalise(state);schedule();}
for(const id of['typeFace','roleCap','roleTracking'])$(id).addEventListener('change',changeRole);
$('resetRole').onclick=()=>{delete state.roles[$('typeRole').value];syncRole();refresh();};
function changeSlot(){const id=$('typeSlot').value,t=P.SLOTS[id];state.slots[id]={cap:Number($('slotCap').value),tracking:Number($('slotTracking').value),...(t.side!=='flat'?{rx:Number($('slotRX').value),ry:Number($('slotRY').value)}:{})};state=E.normalise(state);schedule();}
for(const id of['slotCap','slotTracking','slotRX','slotRY'])$(id).addEventListener('change',changeSlot);
$('resetSlot').onclick=()=>{delete state.slots[$('typeSlot').value];syncSlot();refresh();};
$('outputWidth').onchange=()=>{state.outputWidth=Number($('outputWidth').value);state=E.normalise(state);refresh();};
function referencePreview(){if(!current)return;const ref=R[P.recipe(state.recipe).reference];$('refPreview').replaceChildren();$('guidesPreview').replaceChildren();$('livePreview').style.opacity=mode==='source'?'0':'1';$('compare').hidden=!['overlay','source'].includes(mode);$('refPreview').style.display=['overlay','source'].includes(mode)?'block':'none';$('canvasLabel').textContent={design:'LIVE VECTOR / EDITABLE TEXT',overlay:'WHOLE-LOGO REGISTRATION / NO TEXT WARPING',source:'REGISTERED SOURCE / SAME VIEWPORT',guides:'SHARED BASELINES / FITTED LIVE TYPE'}[mode];
 if(ref){const b=current.viewBox,v=E.node('svg',{viewBox:`${b.x} ${b.y} ${b.w} ${b.h}`});const a=ref.registration||{x:0,y:0,w:ref.w,h:ref.h};const group=E.node('g',{transform:`translate(${alignment.x} ${alignment.y}) translate(338.36631 420.96480) scale(${alignment.scale}) translate(-338.36631 -420.96480)`});group.append(E.node('image',{href:ref.src,x:a.x,y:a.y,width:a.w,height:a.h,preserveAspectRatio:'xMidYMid meet',opacity:mode==='source'?1:Number($('opacity').value)}));v.append(group);$('refPreview').append(v);$('referenceNote').textContent=ref.name+'. '+ref.alignmentNote+' Alignment controls move the entire reference only. The artwork’s aspect ratio is never changed.';}
 if(mode==='guides'){const v=current.svg.cloneNode(true);v.querySelector('metadata')?.remove();v.querySelectorAll('text,[data-layer="frame"],[data-layer="scene"],[data-layer="separators"],[data-layer="tab-shape"],[data-primitive="service-ribbon-primitive"],[data-layer="branch-strip"]').forEach(e=>e.style.opacity='0');const g=v.querySelector('[data-layer="live-lettering"]')||v.querySelector('[data-layer="composition"]');for(const row of current.report){if(!row.slot)continue;const t=E.slot(row.slot,current.state),c=E.curve(t,row.cap,row.curve?.span||t.span);g.append(E.node('path',{d:c.d,fill:'none',stroke:'#c26635','stroke-width':2,'stroke-dasharray':'8 6'}));}
 // IDs must remain unique even when the SVG is overlaid on its source.
 const defs=v.querySelector('defs');defs?.remove();v.querySelectorAll('use').forEach(e=>e.remove());v.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));v.removeAttribute('aria-labelledby');$('guidesPreview').append(v);}
}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;for(const x of document.querySelectorAll('[data-mode]')){const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active));}referencePreview();};
$('opacity').oninput=referencePreview;for(const[k,id]of[['scale','refScale'],['x','refX'],['y','refY']])$(id).oninput=()=>{alignment[k]=Number($(id).value)|| (k==='scale'?1:0);referencePreview();};$('resetCompare').onclick=()=>{alignment={scale:1,x:0,y:0};$('refScale').value=1;$('refX').value=0;$('refY').value=0;referencePreview();};
const stages={natural:'Natural size',tracking:'Spacing reduced','arc-expanded':'Arc expanded','uniform-shrink':'Uniformly reduced'};
function diagnostics(result){$('metricsBody').replaceChildren(...result.report.map(r=>{const tr=document.createElement('tr');const values=[r.role+'|'+(r.slot||'straight text'),P.FACES[r.face].family+'|Weight '+r.weight,r.cap.toFixed(1)+(Math.abs(r.cap-r.preferredCap)>.1?' / '+r.preferredCap.toFixed(1):''),(100*r.width/r.available).toFixed(0)+'%',stages[r.stage]||r.stage];for(const str of values){const td=document.createElement('td'),[a,b]=str.split('|');td.textContent=a;if(b){const sm=document.createElement('small');sm.textContent=b;td.append(sm);}tr.append(td);}return tr;}));$('liveCount').textContent=result.report.length+' coherent text runs';$('warnings').replaceChildren(...result.warnings.filter(x=>x.code!=='FONT_FALLBACK').map(w=>{const p=document.createElement('p');p.className='warning';p.textContent=w.message;return p;}));const missing=result.fontIds.filter(id=>E.fontState.get(id)?.status!=='ready');$('fontStatus').className='font-status '+(missing.length?'bad':'good');$('fontStatus').textContent=missing.length?'Unverified fallback: '+missing.map(id=>P.FACES[id].family+' '+P.FACES[id].weight).join(', ')+'. Load the reference faces before comparing.':result.fontIds.map(id=>P.FACES[id].family+' '+P.FACES[id].weight).join(' · ')+' — exact requested weights loaded; historical font identity remains unverified.';}
function gallery(){const active=P.RECIPES.filter(x=>!x.excluded);$('gallery').replaceChildren(...active.map(r=>{const s=r.id===state.recipe?state:E.recipeState(r.id,state),out=E.makeLogo(s),button=document.createElement('button');button.className='tile'+(r.id===state.recipe?' selected':'');button.dataset.recipe=r.id;button.setAttribute('aria-label','Edit '+r.name);const thumb=document.createElement('span');thumb.className='thumb';thumb.append(out.svg);const title=document.createElement('strong');title.textContent=r.name;const sub=document.createElement('span');sub.className='sub';const full=P.recipe(r.id);sub.textContent=full.crest+' · '+full.tab+' / '+full.confidence;button.append(thumb,title,sub);button.onclick=()=>{startRecipe(r.id);$('drawing').scrollIntoView({behavior:'smooth',block:'center'});};return button;}));$('galleryStatus').textContent=active.length+' recipes · '+Object.keys(P.ROLES).length+' shared type roles';}
async function refresh(){const rev=++revision;try{state=E.normalise(state);const result=await E.render(state);if(rev!==revision)return;current=result;state=result.state;const rec=P.recipe(state.recipe);$('currentTitle').textContent=rec.name;$('compositionPath').textContent=result.crest+' → '+state.tab+' → '+state.layout;$('recipeNote').textContent=rec.confidence+'. '+(rec.extends?'Inherits '+P.recipe(rec.extends).name+'.':'Shared base recipe.');$('livePreview').replaceChildren(result.svg);diagnostics(result);referencePreview();gallery();save();window.BCStudio.current=result;}catch(e){toast(e.message,true);console.error(e);}}
$('loadFonts').onclick=async()=>{const b=$('loadFonts');b.disabled=true;b.textContent='Loading named faces…';try{E.retryFonts();const ids=Object.keys(P.ROLES).map(id=>E.role(id,state).face);const result=await E.ensureFonts(ids,true);await refresh();const missing=result.filter(r=>r.status!=='ready').length;toast(missing?missing+' face(s) could not load. Fallback warnings remain.':'Reference faces loaded. All text has been measured again.',!!missing);}catch(e){toast(e.message,true);}finally{b.disabled=false;b.textContent='Load reference faces online';}};
function download(name,data,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function latest(){clearTimeout(renderTimer);state=E.normalise(state);return E.render(state);}
$('exportSVG').onclick=async()=>{try{const r=await latest();download(state.recipe+'-editable.svg',E.serialise(r),'image/svg+xml');toast(r.warnings.some(x=>x.code==='FONT_FALLBACK')?'SVG exported with a font warning. Install/load the named face on the destination computer.':'Editable SVG exported. Named fonts are referenced, not embedded.');}catch(e){toast(e.message,true);}};
$('exportPNG').onclick=async()=>{const b=$('exportPNG');b.disabled=true;try{const r=await latest(),blob=await E.png(r,state.outputWidth);download(state.recipe+'.png',blob);toast('PNG exported.');}catch(e){toast(e.message,true);}finally{b.disabled=false;}};
function configText(){return JSON.stringify(E.normalise(state),null,2)+'\n';}
$('exportConfig').onclick=()=>download(state.recipe+'-configuration.json',configText(),'application/json');$('importConfig').onclick=()=>$('configFile').click();$('configFile').onchange=async()=>{try{const file=$('configFile').files[0];if(!file)return;if(file.size>1000000)throw Error('Configuration is too large.');const raw=JSON.parse(await file.text());if(raw.version!==5)throw Error('Open a v5 configuration. Earlier per-logo coordinate overrides are not silently migrated.');if(P.recipe(raw.recipe).excluded)throw Error('Fire Control is excluded from this family.');state=E.normalise(raw);sync();await refresh();toast('Configuration and shared rules loaded.');}catch(e){toast(e.message,true);}finally{$('configFile').value='';}};
// Small, dependency-free stored ZIP writer. UTF-8 filenames; no compression.
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zip(entries){const enc=new TextEncoder(),parts=[],directory=[];let offset=0;const u16=(d,p,n)=>d.setUint16(p,n,true),u32=(d,p,n)=>d.setUint32(p,n,true);for(const[name,value]of entries){const fn=enc.encode(name),data=value instanceof Uint8Array?value:enc.encode(value),checksum=crc(data),local=new Uint8Array(30+fn.length),v=new DataView(local.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x800);u32(v,14,checksum);u32(v,18,data.length);u32(v,22,data.length);u16(v,26,fn.length);local.set(fn,30);parts.push(local,data);const central=new Uint8Array(46+fn.length),c=new DataView(central.buffer);u32(c,0,0x02014b50);u16(c,4,20);u16(c,6,20);u16(c,8,0x800);u32(c,16,checksum);u32(c,20,data.length);u32(c,24,data.length);u16(c,28,fn.length);u32(c,42,offset);central.set(fn,46);directory.push(central);offset+=local.length+data.length;}const dsize=directory.reduce((a,b)=>a+b.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);u32(e,0,0x06054b50);u16(e,8,entries.length);u16(e,10,entries.length);u32(e,12,dsize);u32(e,16,offset);return new Blob([...parts,...directory,end],{type:'application/zip'});}
$('exportFamily').onclick=async()=>{const b=$('exportFamily');b.disabled=true;try{await latest();const entries=[];for(const rec of P.RECIPES.filter(x=>!x.excluded)){const s=rec.id===state.recipe?state:E.recipeState(rec.id,state),r=E.makeLogo(s);entries.push([rec.id+'.svg',E.serialise(r)]);}entries.push(['shared-rules.json',JSON.stringify({version:5,roles:state.roles,slots:state.slots},null,2)]);entries.push(['README.txt','Reference-based family. Editable text; no font files embedded. Install the named faces on the destination computer. Historical font identity is not authenticated. Fire Control excluded. The selected recipe includes its current wording; other recipes use their default content with the same shared overrides.\n']);download('bc-ministry-shared-family.zip',zip(entries));toast('Family exported from one set of shared rules.');}catch(e){toast(e.message,true);}finally{b.disabled=false;}};
window.BCStudio={get state(){return E.clone(state);},get mode(){return mode;},current:null,refresh,startRecipe,zip,configText};
sync();refresh();
})();
