import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';

// The SVGs live one level up (generated by ../extract_primitives.py) and the
// comparison references two levels up, so allow Vite to read that far.
const workspace = fileURLToPath(new URL('../..', import.meta.url));

export default defineConfig({
  plugins: [react()],
  base: './',
  build: { chunkSizeWarningLimit: 2000 }, // the SVGs are inlined on purpose
  server: { fs: { allow: [workspace] } },
});
